#!/usr/bin/env python3
"""Generate Passphrase icon bitmap; recolor sunglasses to orange."""
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
# Place source art at tools/assets/passphrase_source.png before regenerating.
SRC = Path(__file__).resolve().parent / "assets" / "passphrase_source.png"
OUT = ROOT / "passphrase_icon_rgb565.h"

OUT_W, OUT_H = 63, 76
CHROMA = 0xF81F
ORANGE = 0xFCA0


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main() -> None:
    im = Image.open(SRC).convert("RGBA")
    bb = im.split()[3].getbbox()
    if bb:
        im = im.crop(bb)

    # Flatten to white background, then threshold to dark-ink strokes.
    bg = Image.new("RGB", im.size, (255, 255, 255))
    bg.paste(im, mask=im.split()[3])
    gray = bg.convert("L")

    iw, ih = gray.size
    scale = min((OUT_W - 2) / iw, (OUT_H - 2) / ih)
    nw = max(1, int(round(iw * scale)))
    nh = max(1, int(round(ih * scale)))
    small = gray.resize((nw, nh), Image.Resampling.LANCZOS)

    canvas = Image.new("L", (OUT_W, OUT_H), 255)
    ox, oy = (OUT_W - nw) // 2, (OUT_H - nh) // 2
    canvas.paste(small, (ox, oy))

    # Stroke mask.
    stroke = [[canvas.getpixel((x, y)) < 170 for x in range(OUT_W)] for y in range(OUT_H)]
    # Content bounds so adjustments scale with icon content, not canvas.
    xs, ys = [], []
    for y in range(OUT_H):
        for x in range(OUT_W):
            if stroke[y][x]:
                xs.append(x)
                ys.append(y)
    if not xs:
        raise SystemExit("No stroke content")
    bx0, bx1 = min(xs), max(xs)
    by0, by1 = min(ys), max(ys)
    bw, bh = (bx1 - bx0 + 1), (by1 - by0 + 1)
    # Unite top hat and brim so they read as one continuous hat shape.
    # (Source icon has a tiny horizontal split after downscaling.)
    hx0 = bx0 + int(bw * 0.21)
    hx1 = bx0 + int(bw * 0.81)
    hy0 = by0 + int(bh * 0.48)
    hy1 = by0 + int(bh * 0.54)
    for y in range(hy0, hy1 + 1):
        for x in range(hx0, hx1 + 1):
            stroke[y][x] = True

    # Sunglasses-only orange tint band (keeps the hat black).
    gx0 = bx0 + int(bw * 0.24)
    gx1 = bx0 + int(bw * 0.78)
    gy0 = by0 + int(bh * 0.66)
    gy1 = by0 + int(bh * 0.83)
    glasses = [[False] * OUT_W for _ in range(OUT_H)]
    for y in range(OUT_H):
        for x in range(OUT_W):
            if stroke[y][x] and gx0 <= x <= gx1 and gy0 <= y <= gy1:
                glasses[y][x] = True

    # 1px inner outline: boundary stays black, interior becomes orange.
    glasses_inner = [[False] * OUT_W for _ in range(OUT_H)]
    for y in range(1, OUT_H - 1):
        for x in range(1, OUT_W - 1):
            if not glasses[y][x]:
                continue
            if (
                glasses[y - 1][x]
                and glasses[y + 1][x]
                and glasses[y][x - 1]
                and glasses[y][x + 1]
            ):
                glasses_inner[y][x] = True

    pixels: list[int] = []
    for y in range(OUT_H):
        for x in range(OUT_W):
            if stroke[y][x]:
                if glasses_inner[y][x]:
                    pixels.append(ORANGE)
                else:
                    pixels.append(0x0000)
            else:
                pixels.append(CHROMA)

    lines = [
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "// Auto-generated by tools/gen_passphrase_icon_rgb565.py",
        f"#define PASSPHRASE_ICON_W {OUT_W}",
        f"#define PASSPHRASE_ICON_H {OUT_H}",
        "#define PASSPHRASE_ICON_CHROMA_KEY 0xF81Fu",
        "",
        "static const uint16_t PASSPHRASE_ICON_RGB565[] PROGMEM = {",
    ]
    for i in range(0, len(pixels), 12):
        chunk = pixels[i : i + 12]
        line = "    " + ", ".join(f"0x{v:04X}u" for v in chunk)
        if i + 12 < len(pixels):
            line += ","
        lines.append(line)
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote", OUT, len(pixels), "pixels")


if __name__ == "__main__":
    main()
