#!/usr/bin/env python3
"""Generate Temporary seed icon (flipped clock) as RGB565 with chroma key."""
from collections import deque
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
# Place source art at tools/assets/temporary_seed_source.png before regenerating.
SRC = Path(__file__).resolve().parent / "assets" / "temporary_seed_source.png"
OUT = ROOT / "temporary_seed_icon_rgb565.h"

OUT_W, OUT_H = 63, 76
CHROMA = 0xF81F


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main() -> None:
    im = Image.open(SRC).convert("RGBA")
    # Flip horizontally so the side dashes are on the right and arrow direction is reversed.
    im = im.transpose(Image.Transpose.FLIP_LEFT_RIGHT)

    # Build an alpha mask from dark strokes on white background.
    bg = Image.new("RGB", im.size, (255, 255, 255))
    bg.paste(im, mask=im.split()[3])
    g = bg.convert("L")
    ink = Image.new("L", im.size, 0)
    ipx = ink.load()
    for y in range(im.size[1]):
        for x in range(im.size[0]):
            ipx[x, y] = 255 if g.getpixel((x, y)) < 160 else 0

    bb = ink.getbbox()
    if not bb:
        raise SystemExit("No icon strokes found")
    crop = ink.crop(bb)
    cw, ch = crop.size
    scale = min((OUT_W - 2) / cw, (OUT_H - 2) / ch)
    nw = max(1, int(round(cw * scale)))
    nh = max(1, int(round(ch * scale)))
    icon = crop.resize((nw, nh), Image.Resampling.LANCZOS)

    canvas = Image.new("L", (OUT_W, OUT_H), 0)
    ox = (OUT_W - nw) // 2
    oy = (OUT_H - nh) // 2
    canvas.paste(icon, (ox, oy), icon)

    # Keep strokes/details black, and fill a true circle constrained to the enclosed interior.
    stroke = [[canvas.getpixel((x, y)) > 110 for x in range(OUT_W)] for y in range(OUT_H)]
    cx, cy = OUT_W // 2, OUT_H // 2
    inside = [[False] * OUT_W for _ in range(OUT_H)]
    # Find a non-stroke seed near center (center can be on a hand).
    seed: tuple[int, int] | None = None
    for r in range(0, max(OUT_W, OUT_H)):
        found = False
        for dy in range(-r, r + 1):
            for dx in range(-r, r + 1):
                if max(abs(dx), abs(dy)) != r:
                    continue
                x, y = cx + dx, cy + dy
                if 0 <= x < OUT_W and 0 <= y < OUT_H and not stroke[y][x]:
                    seed = (x, y)
                    found = True
                    break
            if found:
                break
        if found:
            break
    if seed is not None:
        q: deque[tuple[int, int]] = deque([seed])
        inside[seed[1]][seed[0]] = True
        while q:
            x, y = q.popleft()
            for dx, dy in ((0, 1), (0, -1), (1, 0), (-1, 0)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < OUT_W and 0 <= ny < OUT_H and not stroke[ny][nx] and not inside[ny][nx]:
                    inside[ny][nx] = True
                    q.append((nx, ny))

    # Estimate inner-circle radius from ray hits, ignoring near-center hand pixels.
    import math
    hits: list[float] = []
    for deg in range(0, 360, 2):
        th = math.radians(deg)
        dx, dy = math.cos(th), math.sin(th)
        for r in range(2, 200):
            x = int(round(cx + dx * r))
            y = int(round(cy + dy * r))
            if not (0 <= x < OUT_W and 0 <= y < OUT_H):
                break
            if stroke[y][x]:
                if r > min(OUT_W, OUT_H) * 0.18:  # ignore hand crossings near center
                    hits.append(float(r))
                break
    if hits:
        hits.sort()
        # Lower quartile gives a conservative touch near the inner rim.
        fill_r = max(6.0, hits[len(hits) // 4] - 0.5)
    else:
        fill_r = min(OUT_W, OUT_H) * 0.33
    # Supersampled circle mask to smooth edge jaggies (especially on right side).
    ss = 4
    circle_hi = Image.new("L", (OUT_W * ss, OUT_H * ss), 0)
    draw = ImageDraw.Draw(circle_hi)
    cxs, cys = cx * ss, cy * ss
    r_hi = int(round(fill_r * ss))
    draw.ellipse((cxs - r_hi, cys - r_hi, cxs + r_hi, cys + r_hi), fill=255)
    circle_mask = circle_hi.resize((OUT_W, OUT_H), Image.Resampling.LANCZOS)

    pixels: list[int] = []
    for y in range(OUT_H):
        for x in range(OUT_W):
            in_circle = circle_mask.getpixel((x, y)) > 96
            if stroke[y][x]:
                pixels.append(0x0000)  # black
            elif inside[y][x] and in_circle:
                pixels.append(0xFFFF)  # white fill
            else:
                pixels.append(CHROMA)

    lines = [
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "// Auto-generated by tools/gen_temporary_seed_icon_rgb565.py",
        f"#define TEMPORARY_SEED_ICON_W {OUT_W}",
        f"#define TEMPORARY_SEED_ICON_H {OUT_H}",
        "#define TEMPORARY_SEED_ICON_CHROMA_KEY 0xF81Fu",
        "",
        "static const uint16_t TEMPORARY_SEED_ICON_RGB565[] PROGMEM = {",
    ]
    for i in range(0, len(pixels), 12):
        chunk = pixels[i : i + 12]
        line = "    " + ", ".join(f"0x{c:04X}u" for c in chunk)
        if i + 12 < len(pixels):
            line += ","
        lines.append(line)
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote", OUT, len(pixels), "pixels")


if __name__ == "__main__":
    main()
