#!/usr/bin/env python3
"""Document (orange fill, black strokes) + upward arrow — 58×58 RGB565 (Bitcoin home / Tools scale)."""
from collections import deque
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "assets" / "export_xpub_icon_source.png"
OUT = ROOT / "export_xpub_icon_rgb565.h"

OUT_W = OUT_H = 58
CHROMA = 0xF81F
ORANGE = 0xFCA0
BLACK = 0x0000


def rgb888_to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def flood_exterior(ink):
    h, w = len(ink), len(ink[0])
    ext = [[False] * w for _ in range(h)]
    q = deque()
    for x in range(w):
        for y in (0, h - 1):
            if not ink[y][x] and not ext[y][x]:
                ext[y][x] = True
                q.append((x, y))
    for y in range(h):
        for x in (0, w - 1):
            if not ink[y][x] and not ext[y][x]:
                ext[y][x] = True
                q.append((x, y))
    while q:
        x, y = q.popleft()
        for dx, dy in ((0, 1), (0, -1), (1, 0), (-1, 0)):
            nx, ny = x + dx, y + dy
            if 0 <= nx < w and 0 <= ny < h and not ink[ny][nx] and not ext[ny][nx]:
                ext[ny][nx] = True
                q.append((nx, ny))
    return ext


def build_document_rgb(src_rgba: Image.Image):
    """White bg, classify ink / exterior / interior; return RGB (255,0,255)=chroma, orange interior, black ink."""
    im = src_rgba.convert("RGBA")
    w, h = im.size
    bg = Image.new("RGB", (w, h), (255, 255, 255))
    bg.paste(im, mask=im.split()[3])
    gray = bg.convert("L")
    # Ink: dark strokes (line art)
    ink = [[gray.getpixel((x, y)) < 185 for x in range(w)] for y in range(h)]
    ext = flood_exterior(ink)
    out = Image.new("RGB", (w, h), (255, 0, 255))
    for y in range(h):
        for x in range(w):
            g = gray.getpixel((x, y))
            if g < 185:
                out.putpixel((x, y), (0, 0, 0))
            elif ext[y][x]:
                out.putpixel((x, y), (255, 0, 255))
            else:
                out.putpixel((x, y), (0xFC, 0xA0, 0))
    return out


def paste_arrow(canvas: Image.Image, draw: ImageDraw.ImageDraw):
    """Black upward arrow on the right side of 58×58 canvas."""
    w, h = canvas.size
    # Arrow geometry: tip up, stem down, right side
    cx = w - 9
    cy = h // 2 + 2
    tip = (cx, cy - 14)
    left = (cx - 9, cy + 2)
    right = (cx + 9, cy + 2)
    draw.polygon([tip, left, right], fill=(0, 0, 0))
    draw.rectangle([cx - 3, cy + 2, cx + 3, cy + 16], fill=(0, 0, 0))


def main():
    src = Image.open(SRC).convert("RGBA")
    doc_rgb = build_document_rgb(src)
    # Crop to content (non-chroma)
    w, h = doc_rgb.size
    px = doc_rgb.load()
    xs, ys = [], []
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            if (r, g, b) != (255, 0, 255):
                xs.append(x)
                ys.append(y)
    if not xs:
        raise SystemExit("no content")
    pad = 4
    x0, x1 = max(0, min(xs) - pad), min(w - 1, max(xs) + pad)
    y0, y1 = max(0, min(ys) - pad), min(h - 1, max(ys) + pad)
    doc_rgb = doc_rgb.crop((x0, y0, x1 + 1, y1 + 1))
    dw, dh = doc_rgb.size
    # Reserve ~18px for arrow on the right
    max_doc_w = OUT_W - 20
    scale = min(max_doc_w / dw, (OUT_H - 4) / dh)
    nw, nh = max(1, int(dw * scale)), max(1, int(dh * scale))
    doc_small = doc_rgb.resize((nw, nh), Image.Resampling.LANCZOS)

    canvas = Image.new("RGB", (OUT_W, OUT_H), (255, 0, 255))
    ox = 2
    oy = (OUT_H - nh) // 2
    canvas.paste(doc_small, (ox, oy))
    draw = ImageDraw.Draw(canvas)
    paste_arrow(canvas, draw)

    pixels = []
    px2 = canvas.load()
    for y in range(OUT_H):
        for x in range(OUT_W):
            r, g, b = px2[x, y]
            if (r, g, b) == (255, 0, 255):
                pixels.append(CHROMA)
            elif r < 40 and g < 40 and b < 40:
                pixels.append(BLACK)
            else:
                # orange or AA
                pixels.append(rgb888_to_rgb565(r, g, b))

    lines = [
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "// Auto-generated by tools/gen_export_xpub_icon_rgb565.py (58×58, orange doc / black strokes+arrow).",
        "#define EXPORT_XPUB_ICON_W 58",
        "#define EXPORT_XPUB_ICON_H 58",
        "#define EXPORT_XPUB_ICON_CHROMA_KEY 0xF81Fu",
        "",
        "static const uint16_t EXPORT_XPUB_ICON_RGB565[] PROGMEM = {",
    ]
    for i in range(0, len(pixels), 12):
        chunk = pixels[i : i + 12]
        line = "    " + ", ".join("0x%04Xu" % v for v in chunk)
        line += "," if i + 12 < len(pixels) else ""
        lines.append(line)
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n")
    print("Wrote", OUT, len(pixels), "pixels")


if __name__ == "__main__":
    main()
