#!/usr/bin/env python3
"""Generate Network icon bitmap; side parenthesis arcs in orange."""
from collections import deque
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
# Place source art at tools/assets/network_source.png before regenerating.
SRC = Path(__file__).resolve().parent / "assets" / "network_source.png"
OUT = ROOT / "network_icon_rgb565.h"

OUT_W = OUT_H = 58
CHROMA = 0xF81F
ORANGE = 0xFCA0


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def rgb565_to_rgb888(c: int) -> tuple[int, int, int]:
    return ((c >> 11) & 0x1F) << 3, ((c >> 5) & 0x3F) << 2, (c & 0x1F) << 3


def main() -> None:
    im = Image.open(SRC).convert("RGBA")
    bb = im.split()[3].getbbox()
    if bb:
        im = im.crop(bb)

    bg = Image.new("RGB", im.size, (255, 255, 255))
    bg.paste(im, mask=im.split()[3])
    gray = bg.convert("L")

    # Supersample then downsample to smooth orange arc edges.
    ss = 3
    iw, ih = gray.size
    scale = min((OUT_W - 2) / iw, (OUT_H - 2) / ih)
    nw = max(1, int(round(iw * scale)))
    nh = max(1, int(round(ih * scale)))
    hi_w, hi_h = OUT_W * ss, OUT_H * ss
    small_hi = gray.resize((nw * ss, nh * ss), Image.Resampling.LANCZOS)
    canvas_hi = Image.new("L", (hi_w, hi_h), 255)
    ox, oy = (hi_w - nw * ss) // 2, (hi_h - nh * ss) // 2
    canvas_hi.paste(small_hi, (ox, oy))

    stroke = [[canvas_hi.getpixel((x, y)) < 180 for x in range(hi_w)] for y in range(hi_h)]

    # Label stroke components and detect side arcs.
    comp_id = [[-1] * hi_w for _ in range(hi_h)]
    comps: list[list[tuple[int, int]]] = []
    cid = 0
    for y in range(hi_h):
        for x in range(hi_w):
            if not stroke[y][x] or comp_id[y][x] >= 0:
                continue
            q: deque[tuple[int, int]] = deque([(x, y)])
            comp_id[y][x] = cid
            pts: list[tuple[int, int]] = []
            while q:
                cx, cy = q.popleft()
                pts.append((cx, cy))
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    nx, ny = cx + dx, cy + dy
                    if 0 <= nx < hi_w and 0 <= ny < hi_h and stroke[ny][nx] and comp_id[ny][nx] < 0:
                        comp_id[ny][nx] = cid
                        q.append((nx, ny))
            comps.append(pts)
            cid += 1

    cx = hi_w // 2
    orange_ids: set[int] = set()
    for i, pts in enumerate(comps):
        xs = [p[0] for p in pts]
        x0, x1 = min(xs), max(xs)
        # Side arcs are the components not crossing center; center stem/body crosses center x.
        if x1 < cx - (2 * ss) or x0 > cx + (2 * ss):
            orange_ids.add(i)

    orange_rgb = rgb565_to_rgb888(ORANGE)
    rgba_hi = Image.new("RGBA", (hi_w, hi_h), (0, 0, 0, 0))
    px_hi = rgba_hi.load()
    for y in range(hi_h):
        for x in range(hi_w):
            if not stroke[y][x]:
                continue
            i = comp_id[y][x]
            if i in orange_ids:
                px_hi[x, y] = (orange_rgb[0], orange_rgb[1], orange_rgb[2], 255)
            else:
                px_hi[x, y] = (0, 0, 0, 255)

    rgba = rgba_hi.resize((OUT_W, OUT_H), Image.Resampling.LANCZOS)
    pixels: list[int] = []
    for y in range(OUT_H):
        for x in range(OUT_W):
            r, g, b, a = rgba.getpixel((x, y))
            if a < 80:
                pixels.append(CHROMA)
            else:
                c = rgb888_to_rgb565(r, g, b)
                if c == CHROMA:
                    c ^= 0x20
                pixels.append(c)

    lines = [
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "// Auto-generated by tools/gen_network_icon_rgb565.py",
        "#define NETWORK_ICON_W 58",
        "#define NETWORK_ICON_H 58",
        "#define NETWORK_ICON_CHROMA_KEY 0xF81Fu",
        "",
        "static const uint16_t NETWORK_ICON_RGB565[] PROGMEM = {",
    ]
    for i in range(0, len(pixels), 12):
        chunk = pixels[i : i + 12]
        line = "    " + ", ".join(f"0x{v:04X}u" for v in chunk)
        if i + 12 < len(pixels):
            line += ","
        lines.append(line)
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote", OUT, len(pixels), "pixels")


if __name__ == "__main__":
    main()
