#!/usr/bin/env python3
"""512 PNG → 58×58 RGB565. Arrow = orange; hand + cuff = black; magenta = chroma."""
from pathlib import Path
import collections

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "assets" / "receive_hand_palm_source.png"
OUT = ROOT / "receive_hand_icon_rgb565.h"

W = H = 58
CHROMA = 0xF81F
ORANGE = 0xFCA0
BLACK = 0x0000


def rgb888_to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def luma(r, g, b):
    return (r + g + b) / 3.0


def main():
    src = Image.open(SRC).convert("RGBA")
    src = src.resize((W, H), Image.Resampling.LANCZOS)

    strict = [[0] * W for _ in range(H)]
    lum = [[0.0] * W for _ in range(H)]
    for y in range(H):
        for x in range(W):
            r, g, b, a = src.getpixel((x, y))
            lum[y][x] = luma(r, g, b)
            if a < 128:
                strict[y][x] = 0
            else:
                strict[y][x] = 1 if lum[y][x] <= 145 else 0

    vis = [[False] * W for _ in range(H)]
    comps = []
    for sy in range(H):
        for sx in range(W):
            if not strict[sy][sx] or vis[sy][sx]:
                continue
            q = collections.deque([(sx, sy)])
            vis[sy][sx] = True
            cells = []
            while q:
                x, y = q.popleft()
                cells.append((x, y))
                for dx, dy in ((0, 1), (0, -1), (1, 0), (-1, 0)):
                    nx, ny = x + dx, y + dy
                    if 0 <= nx < W and 0 <= ny < H and strict[ny][nx] and not vis[ny][nx]:
                        vis[ny][nx] = True
                        q.append((nx, ny))
            comps.append(cells)

    xs_all = [x for c in comps for x, _ in c]
    ys_all = [y for c in comps for _, y in c]
    xmin, xmax = min(xs_all), max(xs_all)
    ymin, ymax = min(ys_all), max(ys_all)

    role = ["?"] * len(comps)
    if len(comps) >= 3:
        by_top = sorted(range(len(comps)), key=lambda i: min(y for _, y in comps[i]))
        by_right = sorted(range(len(comps)), key=lambda i: max(x for x, _ in comps[i]), reverse=True)
        arrow_i = by_top[0]
        cuff_i = by_right[0]
        hand_i = None
        for i in range(len(comps)):
            if i != arrow_i and i != cuff_i:
                hand_i = i
                break
        if hand_i is None:
            hand_i = by_top[-1]
        role[arrow_i] = "arrow"
        role[cuff_i] = "cuff"
        role[hand_i] = "hand"

    comp_at = [[-1] * W for _ in range(H)]
    for i, cells in enumerate(comps):
        for x, y in cells:
            comp_at[y][x] = i

    hbb = ymax - ymin + 1
    wbb = xmax - xmin + 1
    arrow_y_cut = ymin + int(0.38 * hbb)
    cuff_x_cut = xmax - max(3, int(0.12 * wbb))

    def pixel_color(px, py):
        r, g, b, a = src.getpixel((px, py))
        if a < 128:
            return CHROMA
        L = lum[py][px]
        if L > 155:
            return CHROMA

        cid = comp_at[py][px]
        if cid < 0 and 40 < L <= 155:
            best_d2 = 999
            best_c = -1
            for dy in range(-3, 4):
                for dx in range(-3, 4):
                    nx, ny = px + dx, py + dy
                    if 0 <= nx < W and 0 <= ny < H and comp_at[ny][nx] >= 0:
                        d2 = dx * dx + dy * dy
                        if d2 < best_d2:
                            best_d2 = d2
                            best_c = comp_at[ny][nx]
            cid = best_c

        def orange_px():
            if L > 95:
                t = (155 - L) / 60.0
                t = max(0.0, min(1.0, t))
                dr = int(0xFC * t + 0xC0 * (1 - t))
                dg = int(0xA0 * t + 0x60 * (1 - t))
                return rgb888_to_rgb565(dr, dg, 0)
            return ORANGE

        def black_px():
            if L > 95:
                t = (155 - L) / 60.0
                t = max(0.0, min(1.0, t))
                br = int(0 * t + 0x28 * (1 - t))
                return rgb888_to_rgb565(br, br, br)
            return BLACK

        if len(comps) >= 3 and cid >= 0:
            if role[cid] == "arrow":
                return orange_px()
            if role[cid] in ("hand", "cuff"):
                return black_px()

        if cid >= 0 and len(comps) == 1:
            if py <= arrow_y_cut:
                return orange_px()
            return black_px()

        if cid >= 0 and len(comps) == 2:
            if py <= arrow_y_cut:
                return orange_px()
            return black_px()

        if cid < 0:
            return CHROMA
        return black_px()

    pixels = [pixel_color(x, y) for y in range(H) for x in range(W)]

    lines = [
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "// Auto-generated by tools/gen_receive_hand_icon_rgb565.py (58×58, arrow orange / hand+cuff black).",
        "#define RECEIVE_HAND_ICON_W 58",
        "#define RECEIVE_HAND_ICON_H 58",
        "#define RECEIVE_HAND_ICON_CHROMA_KEY 0xF81Fu",
        "",
        "static const uint16_t RECEIVE_HAND_ICON_RGB565[] PROGMEM = {",
    ]
    for i in range(0, len(pixels), 12):
        chunk = pixels[i : i + 12]
        line = "    " + ", ".join("0x%04Xu" % v for v in chunk)
        line += "," if i + 12 < len(pixels) else ""
        lines.append(line)
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n")
    print("Wrote", OUT, len(pixels), "pixels; components", len(comps))


if __name__ == "__main__":
    main()
