#!/usr/bin/env python3
"""512 PNG → 58×58 RGB565 (Receive scale). Gear = darker silver; wrench = orange; magenta = chroma."""
from pathlib import Path
import collections

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "assets" / "bitcoin_tools_icon_source.png"
OUT = ROOT / "bitcoin_tools_icon_rgb565.h"

W = H = 58
CHROMA = 0xF81F
# Darker than RGB565_SILVER (0xC618); neutral grey metal
SILVER = 0x9492
ORANGE = 0xFCA0
SILVER_EDGE = 0x632C  # AA / inner shadow toward chroma


def rgb888_to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def rgb565_to_rgb888(c):
    r = ((c >> 11) & 0x1F) << 3
    g = ((c >> 5) & 0x3F) << 2
    b = (c & 0x1F) << 3
    return r, g, b


def luma(r, g, b):
    return (r + g + b) / 3.0


def main():
    src = Image.open(SRC).convert("RGBA")
    src = src.resize((W, H), Image.Resampling.LANCZOS)

    strict = [[0] * W for _ in range(H)]
    lum = [[0.0] * W for _ in range(H)]
    for y in range(H):
        for x in range(W):
            r, g, b, a = src.getpixel((x, y))
            lum[y][x] = luma(r, g, b)
            strict[y][x] = 1 if a >= 128 and lum[y][x] <= 145 else 0

    vis = [[False] * W for _ in range(H)]
    comps = []
    for sy in range(H):
        for sx in range(W):
            if not strict[sy][sx] or vis[sy][sx]:
                continue
            q = collections.deque([(sx, sy)])
            vis[sy][sx] = True
            cells = []
            while q:
                x, y = q.popleft()
                cells.append((x, y))
                for dx, dy in ((0, 1), (0, -1), (1, 0), (-1, 0)):
                    nx, ny = x + dx, y + dy
                    if 0 <= nx < W and 0 <= ny < H and strict[ny][nx] and not vis[ny][nx]:
                        vis[ny][nx] = True
                        q.append((nx, ny))
            comps.append(cells)

    # Larger blob = gear (ring), smaller = wrench
    order = sorted(range(len(comps)), key=lambda i: len(comps[i]), reverse=True)
    role = ["?"] * len(comps)
    if len(comps) >= 2:
        role[order[0]] = "gear"
        role[order[1]] = "wrench"
    elif len(comps) == 1:
        role[0] = "gear"

    comp_at = [[-1] * W for _ in range(H)]
    for i, cells in enumerate(comps):
        for x, y in cells:
            comp_at[y][x] = i

    xs_all = [x for c in comps for x, _ in c]
    ys_all = [y for c in comps for _, y in c]
    def pixel_color(px, py):
        r, g, b, a = src.getpixel((px, py))
        if a < 128:
            return CHROMA
        L = lum[py][px]
        if L > 155:
            return CHROMA

        cid = comp_at[py][px]
        if cid < 0 and 40 < L <= 155:
            best_d2 = 999
            best_c = -1
            for dy in range(-3, 4):
                for dx in range(-3, 4):
                    nx, ny = px + dx, py + dy
                    if 0 <= nx < W and 0 <= ny < H and comp_at[ny][nx] >= 0:
                        d2 = dx * dx + dy * dy
                        if d2 < best_d2:
                            best_d2 = d2
                            best_c = comp_at[ny][nx]
            cid = best_c

        def silver_px():
            if L > 95:
                t = (155 - L) / 60.0
                t = max(0.0, min(1.0, t))
                r0, g0, b0 = rgb565_to_rgb888(SILVER)
                r1, g1, b1 = rgb565_to_rgb888(SILVER_EDGE)
                dr = int(r0 * t + r1 * (1 - t))
                dg = int(g0 * t + g1 * (1 - t))
                db = int(b0 * t + b1 * (1 - t))
                return rgb888_to_rgb565(dr, dg, db)
            return SILVER

        def orange_px():
            if L > 95:
                t = (155 - L) / 60.0
                t = max(0.0, min(1.0, t))
                dr = int(0xFC * t + 0xC0 * (1 - t))
                dg = int(0xA0 * t + 0x60 * (1 - t))
                return rgb888_to_rgb565(dr, dg, 0)
            return ORANGE

        if len(comps) >= 2 and cid >= 0:
            if role[cid] == "gear":
                return silver_px()
            if role[cid] == "wrench":
                return orange_px()

        if cid >= 0 and len(comps) == 1:
            return silver_px()

        if cid < 0:
            return CHROMA
        return silver_px()

    pixels = [pixel_color(x, y) for y in range(H) for x in range(W)]

    lines = [
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "// Auto-generated by tools/gen_bitcoin_tools_icon_rgb565.py (58×58, darker-silver gear / orange wrench).",
        "#define BITCOIN_TOOLS_ICON_W 58",
        "#define BITCOIN_TOOLS_ICON_H 58",
        "#define BITCOIN_TOOLS_ICON_CHROMA_KEY 0xF81Fu",
        "",
        "static const uint16_t BITCOIN_TOOLS_ICON_RGB565[] PROGMEM = {",
    ]
    for i in range(0, len(pixels), 12):
        chunk = pixels[i : i + 12]
        line = "    " + ", ".join("0x%04Xu" % v for v in chunk)
        line += "," if i + 12 < len(pixels) else ""
        lines.append(line)
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n")
    print("Wrote", OUT, len(pixels), "pixels; components", len(comps), role)


if __name__ == "__main__":
    main()
