#!/usr/bin/env python3
"""Generate BIP85 card icon from source image (top interior region in orange)."""
from collections import deque
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
# Place source art at tools/assets/bip85_source.png before regenerating.
SRC = Path(__file__).resolve().parent / "assets" / "bip85_source.png"
OUT = ROOT / "bip85_icon_rgb565.h"

OUT_W = OUT_H = 58
CHROMA = 0xF81F
ORANGE = 0xFCA0


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def rgb565_to_rgb888(c: int) -> tuple[int, int, int]:
    return ((c >> 11) & 0x1F) << 3, ((c >> 5) & 0x3F) << 2, (c & 0x1F) << 3


def flood_outside(solid: list[list[bool]]) -> list[list[bool]]:
    h, w = len(solid), len(solid[0])
    out = [[False] * w for _ in range(h)]
    q: deque[tuple[int, int]] = deque()
    for x in range(w):
        for y in (0, h - 1):
            if not solid[y][x] and not out[y][x]:
                out[y][x] = True
                q.append((x, y))
    for y in range(h):
        for x in (0, w - 1):
            if not solid[y][x] and not out[y][x]:
                out[y][x] = True
                q.append((x, y))
    while q:
        x, y = q.popleft()
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            nx, ny = x + dx, y + dy
            if 0 <= nx < w and 0 <= ny < h and not solid[ny][nx] and not out[ny][nx]:
                out[ny][nx] = True
                q.append((nx, ny))
    return out


def components(mask: list[list[bool]]) -> list[list[tuple[int, int]]]:
    h, w = len(mask), len(mask[0])
    seen = [[False] * w for _ in range(h)]
    comps: list[list[tuple[int, int]]] = []
    for y in range(h):
        for x in range(w):
            if not mask[y][x] or seen[y][x]:
                continue
            q: deque[tuple[int, int]] = deque([(x, y)])
            seen[y][x] = True
            comp: list[tuple[int, int]] = []
            while q:
                cx, cy = q.popleft()
                comp.append((cx, cy))
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    nx, ny = cx + dx, cy + dy
                    if 0 <= nx < w and 0 <= ny < h and mask[ny][nx] and not seen[ny][nx]:
                        seen[ny][nx] = True
                        q.append((nx, ny))
            comps.append(comp)
    return comps


def main() -> None:
    im = Image.open(SRC).convert("RGBA")
    alpha_bb = im.split()[3].getbbox()
    if alpha_bb:
        im = im.crop(alpha_bb)
    # Work in monochrome strokes from source.
    bg = Image.new("RGB", im.size, (255, 255, 255))
    bg.paste(im, mask=im.split()[3])
    gray = bg.convert("L")

    # Resize into icon canvas.
    iw, ih = gray.size
    scale = min((OUT_W - 2) / iw, (OUT_H - 2) / ih)
    nw = max(1, int(round(iw * scale)))
    nh = max(1, int(round(ih * scale)))
    small = gray.resize((nw, nh), Image.Resampling.LANCZOS)
    gcanvas = Image.new("L", (OUT_W, OUT_H), 255)
    ox = (OUT_W - nw) // 2
    oy = (OUT_H - nh) // 2
    gcanvas.paste(small, (ox, oy))

    # Stroke mask.
    solid = [[gcanvas.getpixel((x, y)) < 170 for x in range(OUT_W)] for y in range(OUT_H)]
    outside = flood_outside(solid)
    interior = [[(not solid[y][x]) and (not outside[y][x]) for x in range(OUT_W)] for y in range(OUT_H)]

    # Pick topmost meaningful interior region for orange fill.
    interior_comps = [c for c in components(interior) if len(c) >= 12]
    top_comp = None
    if interior_comps:
        top_comp = min(interior_comps, key=lambda c: sum(p[1] for p in c) / len(c))
    top_set = set(top_comp) if top_comp else set()
    or_r, or_g, or_b = rgb565_to_rgb888(ORANGE)

    pixels: list[int] = []
    for y in range(OUT_H):
        for x in range(OUT_W):
            if solid[y][x]:
                pixels.append(0x0000)  # black strokes
            elif (x, y) in top_set:
                pixels.append(ORANGE)  # top rectangle orange
            elif interior[y][x]:
                pixels.append(0xFFFF)  # interior white
            else:
                pixels.append(CHROMA)

    lines = [
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "// Auto-generated by tools/gen_bip85_icon_rgb565.py",
        "#define BIP85_ICON_W 58",
        "#define BIP85_ICON_H 58",
        "#define BIP85_ICON_CHROMA_KEY 0xF81Fu",
        "",
        "static const uint16_t BIP85_ICON_RGB565[] PROGMEM = {",
    ]
    for i in range(0, len(pixels), 12):
        chunk = pixels[i : i + 12]
        line = "    " + ", ".join(f"0x{v:04X}u" for v in chunk)
        if i + 12 < len(pixels):
            line += ","
        lines.append(line)
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote", OUT, len(pixels), "pixels")


if __name__ == "__main__":
    main()
