#!/usr/bin/env python3
"""UXWing team-collaboration icon → 58×58 RGB565 (orange fill, black strokes; magenta chroma).

Source: https://uxwing.com/team-collaboration-icon/
"""
from collections import deque
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "assets" / "team_collaboration_icon_source.png"
OUT = ROOT / "multisig_settings_icon_rgb565.h"

OUT_W = OUT_H = 58
CHROMA_RGB = (255, 0, 255)
ORANGE_RGB = (0xFC, 0xA0, 0x00)
BLACK_RGB = (0, 0, 0)


def rgb888_to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def flood_exterior(ink):
    h, w = len(ink), len(ink[0])
    ext = [[False] * w for _ in range(h)]
    q = deque()
    for x in range(w):
        for y in (0, h - 1):
            if not ink[y][x] and not ext[y][x]:
                ext[y][x] = True
                q.append((x, y))
    for y in range(h):
        for x in (0, w - 1):
            if not ink[y][x] and not ext[y][x]:
                ext[y][x] = True
                q.append((x, y))
    while q:
        x, y = q.popleft()
        for dx, dy in ((0, 1), (0, -1), (1, 0), (-1, 0)):
            nx, ny = x + dx, y + dy
            if 0 <= nx < w and 0 <= ny < h and not ink[ny][nx] and not ext[ny][nx]:
                ext[ny][nx] = True
                q.append((nx, ny))
    return ext


def main():
    im = Image.open(SRC).convert("RGBA")
    # Soft white matte then downscale for crisp line art.
    bg = Image.new("RGBA", im.size, (255, 255, 255, 255))
    composed = Image.alpha_composite(bg, im).convert("RGB")
    composed = composed.resize((OUT_W, OUT_H), Image.Resampling.LANCZOS)
    gray = composed.convert("L")

    ink = [[gray.getpixel((x, y)) < 170 for x in range(OUT_W)] for y in range(OUT_H)]
    ext = flood_exterior(ink)

    rows = []
    for y in range(OUT_H):
        row = []
        for x in range(OUT_W):
            g = gray.getpixel((x, y))
            if g < 170:
                r, g8, b = BLACK_RGB
            elif ext[y][x]:
                r, g8, b = CHROMA_RGB
            else:
                r, g8, b = ORANGE_RGB
            row.append(rgb888_to_rgb565(r, g8, b))
        rows.append(row)

    chroma = rgb888_to_rgb565(*CHROMA_RGB)
    with OUT.open("w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("#include <Arduino.h>\n\n")
        f.write("// Auto-generated by tools/gen_multisig_settings_icon_rgb565.py\n")
        f.write("// Source: UXWing team-collaboration icon (58×58, orange fill / black strokes).\n")
        f.write(f"#define MULTISIG_SETTINGS_ICON_W {OUT_W}\n")
        f.write(f"#define MULTISIG_SETTINGS_ICON_H {OUT_H}\n")
        f.write(f"#define MULTISIG_SETTINGS_ICON_CHROMA_KEY 0x{chroma:04X}u\n\n")
        f.write("static const uint16_t MULTISIG_SETTINGS_ICON_RGB565[] PROGMEM = {\n")
        flat = [v for row in rows for v in row]
        for i in range(0, len(flat), 12):
            chunk = flat[i : i + 12]
            f.write("    " + ", ".join(f"0x{v:04X}u" for v in chunk) + ",\n")
        f.write("};\n")
    print(f"Wrote {OUT} ({len(flat)} pixels)")


if __name__ == "__main__":
    main()
